language: android
before_script:
 - chmod +x gradlew
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-21.0.0

    # The SDK version used to compile your project
    - android-21

    # Additional components
    - extra-google-google_play_services

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
